export interface Moon {
  name: string
  size: number
  distance: number
  speed: number
  rotationSpeed: number
  texture: string
  description?: string
  diameter?: string
  orbitDistance?: string
  orbitalPeriod?: string
}

export interface PlanetData {
  [key: string]: {
    size: number
    realScale: number
    distance: number
    speed: number
    rotationSpeed: number
    texture: string
    color: string
    moons?: Moon[]
    description: string
    details: {
      diameter: string
      mass: string
      temperature: string
      distance: string
      year: string
      day?: string
      composition?: string
      atmosphere?: string
    }
    facts?: string[]
  }
}

export const planetData: PlanetData = {
  Sol: {
    size: 3.0,
    realScale: 109.0,
    distance: 0,
    speed: 0,
    rotationSpeed: 0.5,
    texture: "sol.jpg",
    color: "#ffff00",
    description:
      "El Sol es una estrella ubicada en el centro de nuestro sistema solar. Es una esfera de plasma caliente, cuya energía es vital para la vida en la Tierra.",
    details: {
      diameter: "1,392,700 km",
      mass: "1.989 × 10^30 kg",
      temperature: "5,500°C en la superficie",
      distance: "0 km",
      year: "N/A",
      day: "25 días terrestres",
      composition: "Hidrógeno (73%), Helio (25%), otros elementos",
      atmosphere: "Corona solar",
    },
    facts: [
      "El Sol contiene el 99.86% de la masa del sistema solar.",
      "La temperatura en el núcleo del Sol alcanza los 15 millones de grados Celsius.",
      "El Sol convierte 4 millones de toneladas de materia en energía cada segundo.",
      "La luz del Sol tarda aproximadamente 8 minutos en llegar a la Tierra.",
    ],
  },
  Mercurio: {
    size: 0.4,
    realScale: 0.38,
    distance: 5,
    speed: 1.6,
    rotationSpeed: 0.1,
    texture: "mercurio.jpg",
    color: "#a6a6a6",
    description:
      "Mercurio es el planeta más cercano al Sol y el más pequeño del sistema solar. Tiene temperaturas extremas debido a la falta de atmósfera densa.",
    details: {
      diameter: "4,880 km",
      mass: "3.301 × 10^23 kg",
      temperature: "-173°C a 427°C",
      distance: "57.9 millones de km",
      year: "88 días terrestres",
      day: "58.6 días terrestres",
      composition: "Rocoso con un gran núcleo de hierro",
      atmosphere: "Casi inexistente, trazas de helio y sodio",
    },
    facts: [
      "Mercurio tiene la órbita más excéntrica de todos los planetas del sistema solar.",
      "A pesar de estar más cerca del Sol, Venus es más caliente debido a su densa atmósfera.",
      "Mercurio tiene cráteres de impacto que contienen hielo en sus regiones polares.",
      "Un día en Mercurio (desde el amanecer hasta el siguiente amanecer) dura aproximadamente 176 días terrestres.",
    ],
  },
  Venus: {
    size: 0.9,
    realScale: 0.95,
    distance: 7,
    speed: 1.2,
    rotationSpeed: 0.08,
    texture: "venus.jpg",
    color: "#e6b35a",
    description:
      "Venus es el segundo planeta desde el Sol y es conocido como el 'gemelo de la Tierra' debido a su tamaño y composición similar.",
    details: {
      diameter: "12,104 km",
      mass: "4.867 × 10^24 kg",
      temperature: "460°C",
      distance: "108.2 millones de km",
      year: "225 días terrestres",
      day: "243 días terrestres (retrógrado)",
      composition: "Rocoso con superficie volcánica",
      atmosphere: "Densa, principalmente dióxido de carbono",
    },
    facts: [
      "Venus gira en dirección contraria a la mayoría de los planetas (rotación retrógrada).",
      "Es el planeta más caliente del sistema solar debido al efecto invernadero extremo.",
      "La presión atmosférica en la superficie de Venus es 92 veces mayor que en la Tierra.",
      "Venus tiene más volcanes que cualquier otro planeta del sistema solar.",
    ],
  },
  Tierra: {
    size: 1.0,
    realScale: 1.0,
    distance: 10,
    speed: 1.0,
    rotationSpeed: 1.0,
    texture: "tierra.jpg",
    color: "#4f6df5",
    moons: [
      {
        name: "Selene",
        size: 0.27,
        distance: 2,
        speed: 2.0,
        rotationSpeed: 0.1,
        texture: "luna.jpg",
        description: "El único satélite natural de la Tierra y el quinto satélite más grande del sistema solar.",
        diameter: "3,474 km",
        orbitDistance: "384,400 km",
        orbitalPeriod: "27.3 días",
      },
    ],
    description:
      "La Tierra es el tercer planeta desde el Sol y el único conocido que tiene agua en estado líquido en su superficie.",
    details: {
      diameter: "12,742 km",
      mass: "5.972 × 10^24 kg",
      temperature: "15°C promedio",
      distance: "149.6 millones de km",
      year: "365.25 días terrestres",
      day: "24 horas",
      composition: "Rocoso con núcleo de hierro y níquel",
      atmosphere: "Nitrógeno (78%), oxígeno (21%), otros gases",
    },
    facts: [
      "La Tierra es el único planeta conocido que alberga vida.",
      "El 71% de la superficie de la Tierra está cubierta por agua.",
      "El campo magnético de la Tierra nos protege de la radiación solar dañina.",
      "La Tierra se formó hace aproximadamente 4.54 mil millones de años.",
    ],
  },
  Marte: {
    size: 0.5,
    realScale: 0.53,
    distance: 15,
    speed: 0.8,
    rotationSpeed: 0.9,
    texture: "marte.jpg",
    color: "#d07a5a",
    moons: [
      {
        name: "Phobos",
        size: 0.1,
        distance: 1.2,
        speed: 3.0,
        rotationSpeed: 0.3,
        texture: "fobos.jpg",
        description: "La luna más grande y cercana a Marte, con forma irregular. Nombre del dios griego del miedo.",
        diameter: "22.2 km",
        orbitDistance: "9,377 km",
        orbitalPeriod: "7.7 horas",
      },
      {
        name: "Deimos",
        size: 0.05,
        distance: 1.8,
        speed: 2.0,
        rotationSpeed: 0.2,
        texture: "deimos.jpg",
        description: "La luna más pequeña y lejana de Marte. Nombre del dios griego del terror.",
        diameter: "12.6 km",
        orbitDistance: "23,460 km",
        orbitalPeriod: "30.3 horas",
      },
    ],
    description:
      "Marte es conocido como el 'planeta rojo' debido a su color característico. Tiene la atmósfera más delgada del sistema solar.",
    details: {
      diameter: "6,779 km",
      mass: "6.417 × 10^23 kg",
      temperature: "-63°C",
      distance: "227.9 millones de km",
      year: "687 días terrestres",
      day: "24.6 horas",
      composition: "Rocoso con óxido de hierro en la superficie",
      atmosphere: "Delgada, principalmente dióxido de carbono",
    },
    facts: [
      "Marte tiene el volcán más grande del sistema solar, el Monte Olimpo.",
      "Hay evidencia de que Marte tuvo agua líquida en su superficie en el pasado.",
      "Marte experimenta tormentas de polvo que pueden cubrir todo el planeta.",
      "Los casquetes polares de Marte están compuestos de hielo de agua y dióxido de carbono congelado.",
    ],
  },
  Júpiter: {
    size: 2.0,
    realScale: 11.2,
    distance: 20,
    speed: 0.4,
    rotationSpeed: 2.0,
    texture: "jupiter.jpg",
    color: "#e0a343",
    moons: [
      {
        name: "Ío",
        size: 0.2,
        distance: 2.5,
        speed: 3.0,
        rotationSpeed: 0.5,
        texture: "io.jpg",
        description: "La luna más volcánicamente activa del sistema solar.",
        diameter: "3,643 km",
        orbitDistance: "421,700 km",
        orbitalPeriod: "1.8 días",
      },
      {
        name: "Europa",
        size: 0.18,
        distance: 3.0,
        speed: 2.5,
        rotationSpeed: 0.4,
        texture: "europa.jpg",
        description: "Luna con una superficie helada que podría albergar un océano subterráneo.",
        diameter: "3,122 km",
        orbitDistance: "671,034 km",
        orbitalPeriod: "3.5 días",
      },
      {
        name: "Ganimedes",
        size: 0.25,
        distance: 3.5,
        speed: 2.0,
        rotationSpeed: 0.3,
        texture: "ganimedes.jpg",
        description: "La luna más grande del sistema solar, más grande que Mercurio.",
        diameter: "5,268 km",
        orbitDistance: "1,070,412 km",
        orbitalPeriod: "7.2 días",
      },
      {
        name: "Calisto",
        size: 0.22,
        distance: 4.0,
        speed: 1.5,
        rotationSpeed: 0.2,
        texture: "calisto.jpg",
        description: "La luna más craterizada del sistema solar.",
        diameter: "4,821 km",
        orbitDistance: "1,882,709 km",
        orbitalPeriod: "16.7 días",
      },
    ],
    description:
      "Júpiter es el planeta más grande del sistema solar. Es un gigante gaseoso compuesto principalmente de hidrógeno y helio.",
    details: {
      diameter: "139,820 km",
      mass: "1.898 × 10^27 kg",
      temperature: "-108°C",
      distance: "778.5 millones de km",
      year: "11.86 años terrestres",
      day: "9.9 horas",
      composition: "Hidrógeno (89%), Helio (10%), otros gases",
      atmosphere: "Hidrógeno, helio, metano, amoníaco",
    },
    facts: [
      "Júpiter tiene más de 80 lunas conocidas.",
      "La Gran Mancha Roja de Júpiter es una tormenta que ha durado más de 300 años.",
      "Júpiter actúa como un 'aspirador cósmico', protegiendo los planetas interiores de asteroides y cometas.",
      "Júpiter tiene un sistema de anillos débiles descubierto en 1979.",
    ],
  },
  Saturno: {
    size: 1.8,
    realScale: 9.4,
    distance: 25,
    speed: 0.3,
    rotationSpeed: 1.8,
    texture: "saturno.jpg",
    color: "#fab95b",
    moons: [
      {
        name: "Titán",
        size: 0.24,
        distance: 3.0,
        speed: 2.0,
        rotationSpeed: 0.3,
        texture: "titan.jpg",
        description: "La segunda luna más grande del sistema solar con una atmósfera densa.",
        diameter: "5,149 km",
        orbitDistance: "1,221,830 km",
        orbitalPeriod: "15.9 días",
      },
      {
        name: "Encélado",
        size: 0.08,
        distance: 2.5,
        speed: 3.0,
        rotationSpeed: 0.5,
        texture: "encelado.jpg",
        description: "Luna helada con géiseres de agua en su polo sur.",
        diameter: "504 km",
        orbitDistance: "238,020 km",
        orbitalPeriod: "1.4 días",
      },
    ],
    description: "Saturno es conocido por sus impresionantes anillos, formados por rocas y polvo.",
    details: {
      diameter: "116,460 km",
      mass: "5.683 × 10^26 kg",
      temperature: "-140°C",
      distance: "1,429 millones de km",
      year: "29.46 años terrestres",
      day: "10.7 horas",
      composition: "Hidrógeno (96%), Helio (3%), otros gases",
      atmosphere: "Hidrógeno, helio, metano, amoníaco",
    },
    facts: [
      "Saturno es menos denso que el agua y flotaría en un océano lo suficientemente grande.",
      "Los anillos de Saturno están compuestos principalmente de partículas de hielo.",
      "Saturno tiene más de 80 lunas conocidas.",
      "Los anillos de Saturno se extienden hasta 282,000 km del planeta pero tienen solo unos pocos metros de espesor.",
    ],
  },
  Urano: {
    size: 1.2,
    realScale: 4.0,
    distance: 30,
    speed: 0.2,
    rotationSpeed: 1.2,
    texture: "urano.jpg",
    color: "#4fd0e7",
    moons: [
      {
        name: "Miranda",
        size: 0.06,
        distance: 2.0,
        speed: 2.5,
        rotationSpeed: 0.4,
        texture: "miranda.jpg",
        description: "Una pequeña luna con una superficie muy variada y extraña.",
        diameter: "471 km",
        orbitDistance: "129,390 km",
        orbitalPeriod: "1.4 días",
      },
      {
        name: "Ariel",
        size: 0.08,
        distance: 2.5,
        speed: 2.0,
        rotationSpeed: 0.3,
        texture: "ariel.jpg",
        description: "Una luna helada con valles y cañones.",
        diameter: "1,158 km",
        orbitDistance: "191,020 km",
        orbitalPeriod: "2.5 días",
      },
      {
        name: "Umbriel",
        size: 0.07,
        distance: 3.0,
        speed: 1.8,
        rotationSpeed: 0.25,
        texture: "umbriel.jpg",
        description: "La luna más oscura de Urano, con una superficie antigua y craterizada.",
        diameter: "1,169 km",
        orbitDistance: "266,000 km",
        orbitalPeriod: "4.1 días",
      },
      {
        name: "Titania",
        size: 0.09,
        distance: 3.5,
        speed: 1.5,
        rotationSpeed: 0.2,
        texture: "titania.jpg",
        description: "La luna más grande de Urano, con cañones y acantilados.",
        diameter: "1,578 km",
        orbitDistance: "435,910 km",
        orbitalPeriod: "8.7 días",
      },
      {
        name: "Oberón",
        size: 0.08,
        distance: 4.0,
        speed: 1.2,
        rotationSpeed: 0.18,
        texture: "oberon.jpg",
        description: "La segunda luna más grande de Urano, muy craterizada.",
        diameter: "1,523 km",
        orbitDistance: "583,520 km",
        orbitalPeriod: "13.5 días",
      },
    ],
    description: "Urano es un gigante gaseoso que se caracteriza por su inclinación extrema de 98 grados.",
    details: {
      diameter: "50,724 km",
      mass: "8.681 × 10^25 kg",
      temperature: "-224°C",
      distance: "2,870 millones de km",
      year: "84 años terrestres",
      day: "17.2 horas",
      composition: "Hidrógeno (83%), Helio (15%), Metano (2%)",
      atmosphere: "Hidrógeno, helio, metano",
    },
    facts: [
      "Urano gira de lado, con una inclinación axial de 98 grados.",
      "Urano fue el primer planeta descubierto con un telescopio en 1781.",
      "Urano tiene anillos débiles descubiertos en 1977.",
      "Las estaciones en Urano duran 21 años terrestres cada una.",
    ],
  },
  Neptuno: {
    size: 1.1,
    realScale: 3.9,
    distance: 35,
    speed: 0.15,
    rotationSpeed: 1.1,
    texture: "neptuno.jpg",
    color: "#4b70dd",
    moons: [
      {
        name: "Tritón",
        size: 0.15,
        distance: 2.5,
        speed: 1.5,
        rotationSpeed: 0.2,
        texture: "triton.jpg",
        description: "La luna más grande de Neptuno, probablemente un objeto del cinturón de Kuiper capturado.",
        diameter: "2,707 km",
        orbitDistance: "354,759 km",
        orbitalPeriod: "5.9 días",
      },
      {
        name: "Nereida",
        size: 0.04,
        distance: 4.0,
        speed: 0.8,
        rotationSpeed: 0.1,
        texture: "nereida.jpg",
        description: "Una pequeña luna irregular con una órbita muy excéntrica.",
        diameter: "340 km",
        orbitDistance: "5,513,818 km",
        orbitalPeriod: "360.1 días",
      },
      {
        name: "Proteo",
        size: 0.03,
        distance: 1.8,
        speed: 2.2,
        rotationSpeed: 0.3,
        texture: "proteo.jpg",
        description: "Una luna irregular de forma extraña, la segunda más grande de Neptuno.",
        diameter: "420 km",
        orbitDistance: "117,647 km",
        orbitalPeriod: "1.1 días",
      },
    ],
    description:
      "Neptuno es el planeta más lejano del sistema solar y es conocido por su color azul debido a los gases en su atmósfera.",
    details: {
      diameter: "49,244 km",
      mass: "1.024 × 10^26 kg",
      temperature: "-214°C",
      distance: "4,500 millones de km",
      year: "165 años terrestres",
      day: "16.1 horas",
      composition: "Hidrógeno (80%), Helio (19%), Metano (1%)",
      atmosphere: "Hidrógeno, helio, metano",
    },
    facts: [
      "Neptuno tiene los vientos más fuertes del sistema solar, alcanzando velocidades de hasta 2,100 km/h.",
      "Neptuno fue descubierto mediante cálculos matemáticos antes de ser observado directamente.",
      "Neptuno tarda 165 años terrestres en completar una órbita alrededor del Sol.",
      "El color azul de Neptuno se debe al metano en su atmósfera.",
    ],
  },
}
